import {advance,composePhrase,createSession,direct} from "./music/engine";
import type {Direction,SessionState} from "./music/types";
import {AudioPerformer} from "./audio";
let state:SessionState=createSession(),running=false,timer:number|undefined;const audio=new AudioPerformer();
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
function render(message?:string){$("section").textContent=state.section.toUpperCase();$("bar").textContent=String(Math.floor(state.beat/4)+1);const tempo=document.querySelector(".transport>div:nth-of-type(2) strong");if(tempo)tempo.textContent=state.bpm+" BPM";$("motif").textContent=state.motif.id+"  ·  "+state.motif.degrees.join(" · ");$("kept").textContent=String(state.kept.length);($("energy") as HTMLProgressElement).value=state.energy;($("tension") as HTMLProgressElement).value=state.tension;if(message)$("message").textContent=message}
function scheduleNext(){if(!running)return;const phrase=composePhrase(state,2);audio.schedule(phrase.events);state=advance(state,phrase.events,phrase.motif,2);render();timer=window.setTimeout(scheduleNext,(8*60/state.bpm)*1000-120)}
async function play(){if(running)return;running=true;$("play").setAttribute("disabled","");$("stop").removeAttribute("disabled");$("status").textContent="PERFORMING";await audio.start(state.beat,state.bpm);scheduleNext();render("Alpha 0.2: groove + phrase memory + critic are running.")}
function stop(){running=false;if(timer)clearTimeout(timer);audio.stop();$("play").removeAttribute("disabled");$("stop").setAttribute("disabled","");$("status").textContent="PAUSED";render("Paused. The musical state is preserved.")}
function command(d:Direction){state=direct(state,d);audio.setTempo(state.bpm);const m={keep:"★ Kept. OTHER will deliberately bring this material back.",more:"MORE: faster, harder, denser — tempo and arrangement are climbing.",less:"LESS: tempo and arrangement are pulling back.",change:"CHANGE: new section, altered motif, groove and tempo."};render(m[d])}
$("play").addEventListener("click",play);$("stop").addEventListener("click",stop);$("keep").addEventListener("click",()=>command("keep"));$("more").addEventListener("click",()=>command("more"));$("less").addEventListener("click",()=>command("less"));$("change").addEventListener("click",()=>command("change"));render();
